Algoritmo "antecessor"
// Disciplina  : Lógica de Programação
// Professor   : Jailson
// Descrição   : Solicitar dois números ao usuário, dividir e exibir o resultado.
// Autor(a)    : Nicole Gregorio Alves
// Data atual  : 29/08/2025
Var
// Seção de Declarações das variáveis
numero1 : inteiro
total : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número: ")
Leia (numero1)
total<-numero1-1
Escreva("O antecessor do valor é: ", total)
Fimalgoritmo